import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign-up",
  description: "Generated by create next app",
};
export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <html lang="en">
        <style>
        {`
          @media (min-width: 1080px) {
            body {
              background: url("/images/login-desktop.png") no-repeat;
              background-size: cover;
              background-position: center;
            }
          }
          @media (min-width: 760px) and (max-width: 820px) {
            body {
              background: url("/images/signup-ipad.png") no-repeat;
            }
          }
          @media (min-width:400px) and (max-width: 420px) {
            body {
              background: url("/images/signup-phone.png") no-repeat;
            }
          }
          @media (max-width: 375px) {
            body {
              background: url("/images/signup-phone-smaller.png") no-repeat;
            }
          }
        `}
      </style>
        <>
          {children}
        </>
      </html>
    );
  }
