import Footer from "@/components/footer/footer";
import "./globals.css";
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import Navbar from "@/components/navbar/navbar";
import ScrollButton from "@/components/backtotop/backToTop";
import ModalProvider from "@/providers/modal-provider";
import getProducts from "@/actions/products/get-all";
import { Product } from "@/types";

const font = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Store Xuan Truong",
  description: "Generated by create next app",
};

interface ProductProps {
  data: Product;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        {children}
        <ScrollButton />
        <Footer />
      </body>
    </html>
  );
}
