import Footer from "@/components/footer/footer";
import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/navbar/navbar";
import ScrollButton from "@/components/backtotop/backToTop";
import ToastProvider from "@/providers/toast-provider";
import { Nunito } from 'next/font/google';

const roboto = Nunito({ weight:"400" , subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Store Xuan Truong",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ToastProvider />
        <Navbar />
        {children}
        <ScrollButton />
        <Footer />
      </body>
    </html>
  );
}
