import Footer from "@/components/footer/footer";
import "./globals.css";
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import Navbar from "@/components/navbar/navbar";
import SlideItem from "@/components/slider-item/slideitem";
import Suggest from "@/components/suggest/Suggest";
import ScrollButton from "@/components/backtotop/backToTop";

const font = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Store Xuan Truong",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        <SlideItem />
        {children}
        <ScrollButton />
        <Suggest />
        <Footer />
      </body>
    </html>
  );
}
