import type { Metadata } from "next";
import { Provider } from "react-redux";
import { store } from "./hooks/store";

export const metadata: Metadata = {
  title: "Store Xuan Truong",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
        <Provider store={store}>
        {children}
        </Provider>
        </>
  );
}
