"use client"
import type { Metadata } from "next";
import { Nunito } from 'next/font/google';
import { Provider } from "react-redux";
import { store } from "./hooks/store";
import Navbar from "@/components/navbar/navbar";
import {  useEffect, useState } from "react";
import Footer from "@/components/footer/footer";


const roboto = Nunito({ weight:"400" , subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Store Xuan Truong",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
        <Provider store={store}>
        {children}
        </Provider>
        </>
  );
}
